[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
  "-Zshare-generics=off",
  "-Zthreads=0",
]

[target.x86_64-pc-windows-gnu]
rustflags = [
  "-Zshare-generics=off",
  "-Zthreads=0",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=/usr/bin/mold",
  "-Z", "share-generics=y",
]
